# This workflow will build and push a .NET Core app to an Azure Web App when a commit is pushed to your default branch.
#
# This workflow assumes you have already created the target Azure Static Web App and have the following secrets set in your repository:
# * AZURE_STATIC_WEB_APPS_API_TOKEN: This is your Azure Static Web Apps API token. You can get this from the Azure portal.
# * HMACSECRET: This is the secret key used to encrypt the JWT token.
# * REDDITCLIENTID: This is the client ID of the Reddit app.
# * REDDITSECRET: This is the secret of the Reddit app.
# * CALLBACKURL: This is the callback URL for the Google PubSubHubbub.
# For instructions see https://docs.microsoft.com/en-us/azure/app-service/quickstart-dotnetcore?tabs=net60&pivots=development-environment-vscode


name: Build and deploy ASP.Net Core app to an Azure Static Web App

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened, closed]
    branches:
      - main

jobs:
  build_and_deploy_job:
    if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.action != 'closed')
    runs-on: ubuntu-latest
    name: Build and Deploy Job
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
          lfs: false
      
      - name: Set up dependency caching for faster builds
        uses: actions/cache@v4
        with:
          path: ~/.nuget/packages
          key: "${{runner.os}}-nuget-${{hashFiles('**/packages.lock.json')}}"
          restore-keys: |
            ${{runner.os}}-nuget-
      
      - name: Build And Deploy
        id: builddeploy
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_ORANGE_SKY_0F13DE403 }}
          repo_token: ${{ secrets.GITHUB_TOKEN }} # Used for Github integrations (i.e. PR comments)
          action: "upload"
          ###### Repository/Build Configurations - These values can be configured to match your app requirements. ######
          # For more information regarding Static Web App workflow configurations, please visit: https://aka.ms/swaworkflowconfig
          app_location: "/" # App source code path
        env:
          HmacSecret: ${{secrets.HMACSECRET}}
          RedditClientId: ${{secrets.REDDITCLIENTID}}
          RedditSecret: ${{secrets.REDDITSECRET}}
          CallbackUrl: ${{secrets.CALLBACKURL}}
        ###### End of Repository/Build Configurations ######

  close_pull_request_job:
    if: github.event_name == 'pull_request' && github.event.action == 'closed'
    runs-on: ubuntu-latest
    name: Close Pull Request Job
    steps:
      - name: Close Pull Request
        id: closepullrequest
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_ORANGE_SKY_0F13DE403 }}
          action: "close"
